# Generated by Django 3.2.1 on 2021-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(default='https://img.icons8.com/material-rounded/200/000000/user.png', max_length=9999),
        ),
    ]
