# Generated by Django 3.2.1 on 2021-05-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210513_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='item',
        ),
        migrations.CreateModel(
            name='SearchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchItem', models.CharField(blank=True, max_length=255, null=True)),
                ('searchHistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.searchhistory')),
            ],
        ),
    ]
