# Generated by Django 3.2.1 on 2021-05-14 01:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('apartment_number', models.CharField(blank=True, max_length=255)),
                ('additional_information', models.CharField(blank=True, max_length=999)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=20)),
            ],
        ),
    ]
