# Generated by Django 3.2.1 on 2021-05-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longDescription', models.CharField(max_length=999)),
                ('nutritionalValue', models.CharField(max_length=999)),
                ('cereal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.cereal')),
            ],
        ),
    ]
