# Generated by Django 3.2.1 on 2021-05-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='customer',
            new_name='product',
        ),
    ]
